name: Build and Release Apache HTTPD

on:
  repository_dispatch:
    types: [apache_httpd_release]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cmake

    - name: Build Apache HTTPD
      run: |
        # Download and extract Apache HTTPD source code
        Invoke-WebRequest -Uri "https://downloads.apache.org/httpd/httpd-${{ steps.get_version.outputs.VERSION }}.tar.gz" -OutFile "httpd.tar.gz"
        tar -xzvf httpd.tar.gz
    
        # Set up build environment
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    
        # Configure Apache HTTPD
        cd "httpd-${{ steps.get_version.outputs.VERSION }}"
        perl srclib\apr\build\lineends.pl
        perl srclib\apr\build\cvtdsp.pl -2005
        perl srclib\apr-util\build\lineends.pl
        perl srclib\apr-util\build\cvtdsp.pl -2005
    
        # Build Apache HTTPD
        msbuild /p:Configuration=Release /p:Platform=x64 /p:OutDir=out\httpd\ Apache.Httpd.sln
    
        # Package the build
        Compress-Archive -Path out\httpd\* -DestinationPath ${{ github.workspace }}\httpd-${{ steps.get_version.outputs.VERSION }}.zip

    - name: Get the version
      id: get_version
      run: |
        VERSION=$(grep -oP '(?<=AP_SERVER_BASEVERSION "Apache/).*(?=")' include/ap_release.h)
        echo "::set-output name=VERSION::$VERSION"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
